---
- name: Install Logstash
  yum:
    name: logstash
    state: present
    disable_gpg_check: true

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable Logstash
  systemd:
    name: logstash.service
    enabled: yes
