all:
  hosts:
    node_1:
      ansible_host: 192.168.1.160
      node_name: "Elk1"
      node_roles: [master]
    node_2:
      ansible_host: 192.168.1.161
      node_name: "Elk2"
      node_roles: [data, ingest]
    node_3:
      ansible_host: 192.168.1.162
      node_name: "Elk3"
      node_roles: [data, ingest]
  vars:
    # For commenting master.node line
    node_pattern: "Elk"

elasticsearch:
  children:
    ## Only one node is bootstrap
    bootstrap_node:
      hosts:
        node_1:
    ## Other nodes are regular
    regular_nodes:
      hosts:
        node_2:
        node_3:

kibana:
  hosts:
    node_1:

logstash:
  hosts:
    node_1:
