---
- hosts: elasticsearch
  gather_facts: yes
  become: yes
  roles:
    - name: elasticsearch
      tags: elasticsearch

- hosts: kibana
  gather_facts: yes
  become: yes
  roles:
    - name: kibana
      tags: kibana

- hosts: logstash
  gather_facts: yes
  become: yes
  roles:
    - name: logstash
      tags: logstash
